#!/usr/bin/env python3
"""Migrate Part 2 schema from sqlite into Postgres/Neon.

Creates missing tables used by the live backend:
- users additions: full_name, email, is_first_login
- user_tokens
- sections
- groups
- students
- record.student_id

Run after the base `migrate_sqlite_to_pg.py` migration.
"""
from __future__ import annotations

import argparse
import os
import sqlite3
import sys

try:
    import psycopg2
    from psycopg2.extras import execute_values
except Exception:
    print("psycopg2 is required. Install with: pip install psycopg2-binary")
    raise


def ensure_column(cur, table: str, column: str, ddl: str) -> None:
    cur.execute(
        """
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = %s AND column_name = %s
        """,
        (table, column),
    )
    if cur.fetchone() is None:
        cur.execute(f"ALTER TABLE {table} ADD COLUMN {column} {ddl}")


def create_schema(pg_conn) -> None:
    cur = pg_conn.cursor()

    # users additions required by current backend code
    ensure_column(cur, "users", "full_name", "TEXT")
    ensure_column(cur, "users", "email", "TEXT")
    ensure_column(cur, "users", "is_first_login", "BOOLEAN NOT NULL DEFAULT FALSE")
    # Preserve the original data model, which may store section names like BSIT-3A.
    cur.execute("ALTER TABLE users ALTER COLUMN section TYPE TEXT USING section::text")

    # token storage for remember-me / verification flows
    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS user_tokens (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            token TEXT NOT NULL UNIQUE,
            expires_at TIMESTAMP NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    cur.execute("CREATE INDEX IF NOT EXISTS idx_user_tokens_token ON user_tokens(token)")
    cur.execute("CREATE INDEX IF NOT EXISTS idx_user_tokens_user_id ON user_tokens(user_id)")

    # Part 2 tables
    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS sections (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            teacher_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            name TEXT NOT NULL,
            school_year TEXT,
            semester TEXT,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )

    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS groups (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            section_id INTEGER NOT NULL REFERENCES sections(id) ON DELETE CASCADE,
            group_number INTEGER NOT NULL,
            group_name TEXT NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )

    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS students (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
            group_id INTEGER NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
            stud_number TEXT NOT NULL,
            surname TEXT NOT NULL,
            first_name TEXT NOT NULL,
            middle_initial TEXT,
            email TEXT NOT NULL,
            temp_password TEXT,
            is_first_login BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )

    # record.student_id for student dashboard links
    ensure_column(cur, "record", "student_id", "INTEGER REFERENCES students(id) ON DELETE CASCADE")

    # Useful indexes for the live queries
    cur.execute("CREATE INDEX IF NOT EXISTS idx_sections_teacher_id ON sections(teacher_id)")
    cur.execute("CREATE INDEX IF NOT EXISTS idx_groups_section_id ON groups(section_id)")
    cur.execute("CREATE INDEX IF NOT EXISTS idx_students_group_id ON students(group_id)")
    cur.execute("CREATE INDEX IF NOT EXISTS idx_students_stud_number ON students(stud_number)")
    cur.execute("CREATE INDEX IF NOT EXISTS idx_students_email ON students(email)")
    cur.execute("CREATE INDEX IF NOT EXISTS idx_record_student_id ON record(student_id)")

    pg_conn.commit()
    cur.close()


def ensure_auto_id(pg_conn, table: str) -> None:
    cur = pg_conn.cursor()
    seq_name = f"{table}_id_seq"

    cur.execute(f"CREATE SEQUENCE IF NOT EXISTS {seq_name}")
    cur.execute(
        f"SELECT COALESCE(MAX(id), 0) FROM {table}"
    )
    max_id = cur.fetchone()[0] or 0
    cur.execute(f"SELECT setval(%s, %s, true)", (seq_name, max_id))
    cur.execute(
        f"ALTER TABLE {table} ALTER COLUMN id SET DEFAULT nextval(%s)",
        (seq_name,)
    )
    try:
        cur.execute(f"ALTER SEQUENCE {seq_name} OWNED BY {table}.id")
    except Exception:
        pass
    pg_conn.commit()
    cur.close()


def copy_table(sql_conn, pg_conn, table_name: str, columns: list[str], transform=None) -> int:
    src = sql_conn.cursor()
    src.execute(f"SELECT {', '.join(columns)} FROM {table_name}")
    rows = src.fetchall()
    if not rows:
        print(f"No rows found in {table_name}")
        return 0

    data = []
    for row in rows:
        values = [row[col] for col in columns]
        if transform:
            values = transform(row, values)
        data.append(tuple(values))

    placeholders = ",".join(["%s"] * len(columns))
    insert_sql = f"INSERT INTO {table_name} ({', '.join(columns)}) VALUES %s ON CONFLICT DO NOTHING"
    cur = pg_conn.cursor()
    execute_values(cur, insert_sql, data, template=None, page_size=100)
    pg_conn.commit()
    cur.close()
    print(f"Copied {len(data)} rows into {table_name}")
    return len(data)


def sqlite_table_exists(sql_conn, table_name: str) -> bool:
    cur = sql_conn.cursor()
    cur.execute("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?", (table_name,))
    exists = cur.fetchone() is not None
    cur.close()
    return exists


def copy_users(sql_conn, pg_conn) -> None:
    if not sqlite_table_exists(sql_conn, "users"):
        print("No source users table found; skipping")
        return

    def transform(row, values):
        # Source sqlite may not have full_name/email/is_first_login yet.
        user_id, is_teacher, stud_id, first_name, last_name, year, section, group_name, password, created_at, updated_at = values
        full_name = row["full_name"] if "full_name" in row.keys() else None
        email = row["email"] if "email" in row.keys() else None
        is_first_login = row["is_first_login"] if "is_first_login" in row.keys() else 0
        if not full_name:
            full_name = f"{first_name} {last_name}".strip()
        section_text = None if section is None else str(section)
        return [user_id, bool(is_teacher), stud_id, first_name, last_name, year, section_text, group_name, password, created_at, updated_at, full_name, email, bool(is_first_login)]

    # Need to include extra columns if present in target. Build from source schema dynamically.
    src = sql_conn.cursor()
    src.execute("PRAGMA table_info(users)")
    source_cols = [r[1] for r in src.fetchall()]
    src.close()

    select_cols = ["id", "is_teacher", "stud_id", "first_name", "last_name", "year", "section", "group_name", "password", "created_at", "updated_at"]
    base_rows = sql_conn.cursor()
    base_rows.execute(f"SELECT {', '.join(select_cols)} FROM users")
    rows = base_rows.fetchall()
    base_rows.close()

    data = []
    for row in rows:
        full_name = row["first_name"] if False else None
        # Optional source fields if they exist.
        extra_cur = sql_conn.cursor()
        extra_cur.execute("SELECT * FROM users WHERE id = ?", (row["id"],))
        full_row = extra_cur.fetchone()
        extra_cur.close()

        full_name = full_row["full_name"] if "full_name" in full_row.keys() and full_row["full_name"] else f"{row['first_name']} {row['last_name']}".strip()
        email = full_row["email"] if "email" in full_row.keys() else None
        is_first_login = full_row["is_first_login"] if "is_first_login" in full_row.keys() else 0

        data.append((
            row["id"],
            bool(row["is_teacher"]),
            row["stud_id"],
            row["first_name"],
            row["last_name"],
            row["year"],
            row["section"],
            row["group_name"],
            row["password"],
            row["created_at"],
            row["updated_at"],
            full_name,
            email,
            bool(is_first_login),
        ))

    cur = pg_conn.cursor()
    execute_values(
        cur,
        "INSERT INTO users (id, is_teacher, stud_id, first_name, last_name, year, section, group_name, password, created_at, updated_at, full_name, email, is_first_login) VALUES %s ON CONFLICT (id) DO NOTHING",
        data,
        template=None,
        page_size=100,
    )
    pg_conn.commit()
    cur.close()
    print(f"Copied {len(data)} rows into users")


def copy_record_with_student_id(sql_conn, pg_conn) -> None:
    if not sqlite_table_exists(sql_conn, "record"):
        print("No source record table found; skipping")
        return

    # Copy record rows and preserve student_id when available in source sqlite.
    src = sql_conn.cursor()
    src.execute("PRAGMA table_info(record)")
    record_cols = [r[1] for r in src.fetchall()]
    src.close()

    has_student_id = "student_id" in record_cols
    select_cols = ["id", "stud_id", "date", "type_of_undertaking", "total_score", "score", "remarks", "created_at", "updated_at"]
    if has_student_id:
        select_cols.insert(2, "student_id")

    cur = sql_conn.cursor()
    cur.execute(f"SELECT {', '.join(select_cols)} FROM record")
    rows = cur.fetchall()
    cur.close()

    data = []
    for row in rows:
        student_id = row["student_id"] if has_student_id else None
        data.append(
            (
                row["id"],
                row["stud_id"],
                row["date"],
                row["type_of_undertaking"],
                row["total_score"],
                row["score"],
                row["remarks"],
                row["created_at"],
                row["updated_at"],
                student_id,
            )
        )

    cur = pg_conn.cursor()
    execute_values(
        cur,
        "INSERT INTO record (id, stud_id, date, type_of_undertaking, total_score, score, remarks, created_at, updated_at, student_id) VALUES %s ON CONFLICT (id) DO NOTHING",
        data,
        template=None,
        page_size=100,
    )
    pg_conn.commit()
    cur.close()
    print(f"Copied {len(data)} rows into record")


def copy_sections_groups_students(sql_conn, pg_conn) -> None:
    for table_name in ["sections", "groups", "students"]:
        if not sqlite_table_exists(sql_conn, table_name):
            print(f"No source {table_name} table found; skipping copy for that table")

    # sections
    if sqlite_table_exists(sql_conn, "sections"):
        copy_table(sql_conn, pg_conn, "sections", ["id", "teacher_id", "name", "school_year", "semester", "created_at"])

    # groups
    if sqlite_table_exists(sql_conn, "groups"):
        copy_table(sql_conn, pg_conn, "groups", ["id", "section_id", "group_number", "group_name", "created_at"])

    # students
    if sqlite_table_exists(sql_conn, "students"):
        copy_table(
            sql_conn,
            pg_conn,
            "students",
            ["id", "user_id", "group_id", "stud_number", "surname", "first_name", "middle_initial", "email", "temp_password", "is_first_login", "created_at"],
            transform=lambda row, values: [
                values[0],
                values[1],
                values[2],
                values[3],
                values[4],
                values[5],
                values[6],
                values[7],
                values[8],
                bool(values[9]),
                values[10],
            ],
        )

    # user_tokens if source table exists
    if sqlite_table_exists(sql_conn, "user_tokens"):
        copy_table(sql_conn, pg_conn, "user_tokens", ["id", "user_id", "token", "expires_at", "created_at"])
    else:
        print("No source user_tokens table found; skipping")


def bump_sequences(pg_conn) -> None:
    cur = pg_conn.cursor()
    for table in ["users", "record", "sections", "groups", "students", "user_tokens"]:
        try:
            cur.execute(f"SELECT COALESCE(MAX(id), 0) FROM {table}")
            max_id = cur.fetchone()[0]
            cur.execute(f"SELECT pg_get_serial_sequence(%s, %s)", (table, "id"))
            seq = cur.fetchone()[0]
            if seq:
                cur.execute(f"SELECT setval(%s, %s, true)", (seq, max_id))
        except Exception:
            pg_conn.rollback()
    pg_conn.commit()
    cur.close()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--sqlite-file", required=True)
    parser.add_argument("--pg", default=os.environ.get("DATABASE_URL"))
    args = parser.parse_args()

    if not args.pg:
        print("Postgres connection string required: pass --pg or set DATABASE_URL")
        return 1

    sqlite_path = args.sqlite_file
    if not os.path.exists(sqlite_path):
        print(f"SQLite file not found: {sqlite_path}")
        return 1

    print(f"Opening sqlite: {sqlite_path}")
    sql_conn = sqlite3.connect(sqlite_path)
    sql_conn.row_factory = sqlite3.Row

    print("Connecting to Postgres")
    pg_conn = psycopg2.connect(args.pg)

    try:
        create_schema(pg_conn)
        ensure_auto_id(pg_conn, "users")
        ensure_auto_id(pg_conn, "record")
        copy_users(sql_conn, pg_conn)
        copy_record_with_student_id(sql_conn, pg_conn)
        copy_sections_groups_students(sql_conn, pg_conn)
        bump_sequences(pg_conn)
        print("Part 2 migration completed successfully")
        return 0
    finally:
        try:
            sql_conn.close()
        except Exception:
            pass
        try:
            pg_conn.close()
        except Exception:
            pass


if __name__ == "__main__":
    raise SystemExit(main())
